# -*- coding: utf-8 -*-
"""AnalisisDataPenjualan_BIAnalyst

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IYWWnqloXXFoWfCEeATIe-Nr8CDkWu2
"""

# Install library yang dibutuhkan
!pip install pandas openpyxl

# Import library
import pandas as pd

# Upload file (bisa lewat panel di kiri Colab)
customers = pd.read_excel("/content/drive/MyDrive/Dataset Task 5 (1)/Customers.xlsx")
orders = pd.read_excel("/content/drive/MyDrive/Dataset Task 5 (1)/Orders.xlsx")
products = pd.read_excel("/content/drive/MyDrive/Dataset Task 5 (1)/Products.xlsx")
product_category = pd.read_excel("/content/drive/MyDrive/Dataset Task 5 (1)/ProductCategory.xlsx")

# 1️⃣ Bersihkan kolom email (hapus tambahan "#mailto...")
customers["CustomerEmail"] = customers["CustomerEmail"].str.split("#mailto").str[0]

# 2️⃣ Gabungkan tabel berdasarkan relasi yang sesuai
master = (
    orders
    .merge(customers, on="CustomerID", how="left")
    .merge(products, on="ProdNumber", how="left")
    .merge(product_category, left_on="Category", right_on="CategoryID", how="left")
)

# 3️⃣ Pilih kolom yang dibutuhkan sesuai instruksi tugas
master = master[[
    "CustomerEmail", "CustomerCity", "Date", "Quantity",
    "ProdName", "Price", "CategoryName"
]]

# 4️⃣ Hitung kolom total_sales
master["TotalSales"] = master["Quantity"] * master["Price"]

# 5️⃣ Ganti nama kolom biar sesuai format final
master = master.rename(columns={
    "CustomerEmail": "cust_email",
    "CustomerCity": "cust_city",
    "Date": "order_date",
    "Quantity": "order_qty",
    "ProdName": "product_name",
    "Price": "product_price",
    "CategoryName": "category_name",
    "TotalSales": "total_sales"
})

# 6️⃣ Tampilkan hasil (5 baris pertama)
master.head()

master.to_csv("/content/master_sales.csv", index=False)

# --- ANALISIS DATA PENJUALAN ---

print("📊 --- ANALISIS DATA PENJUALAN ---\n")

# 1️⃣ Total keseluruhan sales dan quantity
total_sales = master["total_sales"].sum()
total_qty = master["order_qty"].sum()
print(f"Total keseluruhan sales: Rp {total_sales:,.2f}")
print(f"Total keseluruhan quantity: {total_qty:,} item\n")

# 2️⃣ Total sales berdasarkan kategori produk
sales_by_category = (
    master.groupby("category_name")["total_sales"]
    .sum()
    .sort_values(ascending=False)
)
print("💡 Total Sales Berdasarkan Kategori Produk:")
print(sales_by_category)
print()

# 3️⃣ Total quantity berdasarkan kategori produk
qty_by_category = (
    master.groupby("category_name")["order_qty"]
    .sum()
    .sort_values(ascending=False)
)
print("📦 Total Quantity Berdasarkan Kategori Produk:")
print(qty_by_category)
print()

# 4️⃣ Total sales berdasarkan kota (Top 10)
sales_by_city = (
    master.groupby("cust_city")["total_sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
print("🏙️ 10 Kota dengan Total Sales Tertinggi:")
print(sales_by_city)
print()

# 5️⃣ Top 5 kategori dengan sales tertinggi
top5_sales = sales_by_category.head(5)
print("🔥 Top 5 Kategori Produk dengan Sales Tertinggi:")
print(top5_sales)
print()

# 6️⃣ Top 5 kategori dengan quantity tertinggi
top5_qty = qty_by_category.head(5)
print("⭐ Top 5 Kategori Produk dengan Quantity Tertinggi:")
print(top5_qty)
print()

print("✅ Analisis ringkas selesai. Data siap untuk visualisasi di Looker Studio.")